PRAGMA foreign_keys = ON;

-- KENDALI Natara — Import database karyawan dari Data_Base_Karyawan.pdf
-- Kolom kosong pada sumber dipertahankan kosong agar dapat dilengkapi kemudian.

INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-005','{"username":"irhamyuskhann","password":"","name":"IRHAM YUSKHAN","nip":"","jabatan":"HEAD OF SUPPORTING","role":"Head of Supporting","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"irhamyuskhann@gmail.com","tglMasuk":"10/1/2025","status":"Aktif","departemen":"Supporting","statusPegawai":"KONTRAK","sourceNo":5,"sourceDepartemen":"SUPPORTING","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;
INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-017','{"username":"","password":"","name":"Muhammad Rezky","nip":"","jabatan":"ESTIMATOR","role":"Estimator","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"","tglMasuk":"4/2/2026","status":"Aktif","departemen":"Engineering","statusPegawai":"KONTRAK","sourceNo":17,"sourceDepartemen":"ENGGENERING","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;
INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-020','{"username":"muhammadsyawal26001","password":"","name":"MUHAMMAD SYAWAL","nip":"","jabatan":"HEAD BISNIS UNIT","role":"Manager Konstruksi","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"muhammadsyawal26001@gmail.com","tglMasuk":"4/9/2025","status":"Aktif","departemen":"","statusPegawai":"KONTRAK","sourceNo":20,"sourceDepartemen":"","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;
INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-021','{"username":"sayyidtriwardhana","password":"","name":"SAYYID TRIWARDHANA","nip":"","jabatan":"PROJECT MANAGER","role":"Superintendent","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"sayyidtriwardhana@gmail.com","tglMasuk":"6/30/2025","status":"Aktif","departemen":"Operational","statusPegawai":"KONTRAK","sourceNo":21,"sourceDepartemen":"operational","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;
INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-022','{"username":"ammankzonk","password":"","name":"SUHARMAN","nip":"","jabatan":"PELAKSANA LAPANGAN","role":"Pelaksana Lapangan","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"Ammankzonk@gmail.com","tglMasuk":"8/21/2025","status":"Aktif","departemen":"Operational","statusPegawai":"KONTRAK","sourceNo":22,"sourceDepartemen":"operational","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;
INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-023','{"username":"muhammadhilalp765","password":"","name":"MUHAMMAD HILAL PRIYATAMA","nip":"","jabatan":"PROJECT MANAGER","role":"Superintendent","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"muhammadhilalp765@gmail.com","tglMasuk":"9/26/2025","status":"Aktif","departemen":"Operational","statusPegawai":"KONTRAK","sourceNo":23,"sourceDepartemen":"operational","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;
INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-024','{"username":"raikah536","password":"","name":"GAZALI TRY SULISTIO NIRMAWAN","nip":"","jabatan":"PELAKSANA LAPANGAN","role":"Pelaksana Lapangan","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"raikah536@gmail.com","tglMasuk":"8/27/2025","status":"Aktif","departemen":"Operational","statusPegawai":"KONTRAK","sourceNo":24,"sourceDepartemen":"operational","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;
INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-026','{"username":"suskuber8","password":"","name":"AHMAD IRFAN FADAD","nip":"","jabatan":"PELAKSANA LAPANGAN","role":"Pelaksana Lapangan","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"suskuber8@gmail.com","tglMasuk":"12/2/2025","status":"Aktif","departemen":"Operational","statusPegawai":"KONTRAK","sourceNo":26,"sourceDepartemen":"operational","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;
INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-028','{"username":"wirakusumahahmad7","password":"","name":"WIRA KUSUMA AHMAD","nip":"","jabatan":"HEAD OF ENGGENERING","role":"Head of Engineering","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"wirakusumahahmad7@gmail.com","tglMasuk":"11/27/2025","status":"Aktif","departemen":"Engineering","statusPegawai":"KONTRAK","sourceNo":28,"sourceDepartemen":"ENGGENERING","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;
INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-029','{"username":"amuhmalfikram","password":"","name":"A. MUH. MALFIKRAM AL HILAL","nip":"","jabatan":"ADMIN TEKNIK","role":"Admin Teknik","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"amuhmalfikram@gmail.com","tglMasuk":"8/22/2025","status":"Aktif","departemen":"Engineering","statusPegawai":"KONTRAK","sourceNo":29,"sourceDepartemen":"ENGGENERING","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;
INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-030','{"username":"aanmks0326","password":"","name":"ANDI MUH RIFLY FAUZAN","nip":"","jabatan":"PELAKSANA LAPANGAN","role":"Pelaksana Lapangan","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"aanmks0326@gmail.com","tglMasuk":"1/14/2026","status":"Aktif","departemen":"Operational","statusPegawai":"KONTRAK","sourceNo":30,"sourceDepartemen":"operational","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;
INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-031','{"username":"muhammdnurfikry","password":"","name":"MUH. NUR FIKRY","nip":"","jabatan":"PELAKSANA LAPANGAN","role":"Pelaksana Lapangan","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"muhammdnurfikry@gmail.com","tglMasuk":"1/5/2026","status":"Aktif","departemen":"Operational","statusPegawai":"KONTRAK","sourceNo":31,"sourceDepartemen":"operational","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;
INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-033','{"username":"","password":"","name":"RAIHAN AFHATATUR","nip":"","jabatan":"PELAKSANA LAPANGAN","role":"Pelaksana Lapangan","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"","tglMasuk":"1/31/2026","status":"Aktif","departemen":"Operational","statusPegawai":"KONTRAK","sourceNo":33,"sourceDepartemen":"operational","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;
INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-034','{"username":"raihanfahrulrf","password":"","name":"RAIHAN FAHRUL","nip":"","jabatan":"Quality Control","role":"QC Inspector","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"raihanfahrulrf@gmail.com","tglMasuk":"2/18/2026","status":"Aktif","departemen":"Supporting","statusPegawai":"KONTRAK","sourceNo":34,"sourceDepartemen":"SUPPORTING","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;
INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-035','{"username":"dzuljob","password":"","name":"Zulkarnaen","nip":"","jabatan":"PROJECT MANAGER","role":"Superintendent","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"dzuljob@gmail.com","tglMasuk":"3/5/2026","status":"Aktif","departemen":"Operational","statusPegawai":"KONTRAK","sourceNo":35,"sourceDepartemen":"operational","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;
INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-036','{"username":"amirullahca","password":"","name":"AMIRULLAH","nip":"","jabatan":"AKADEMI TUKANG INDONESIA","role":"","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"amirullahca@gmail.com","tglMasuk":"4/6/2026","status":"Aktif","departemen":"Supporting","statusPegawai":"KONTRAK","sourceNo":36,"sourceDepartemen":"SUPPORTING","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;
INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-037','{"username":"yusrilmahendraaa12","password":"","name":"A. YUSRIL MAHENDRA","nip":"","jabatan":"DRAFTER","role":"Drafter/BIM","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"yusrilmahendraaa12@gmail.com","tglMasuk":"4/13/2026","status":"Aktif","departemen":"Engineering","statusPegawai":"KONTRAK","sourceNo":37,"sourceDepartemen":"ENGGENERING","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;
INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-038','{"username":"andiarahm16","password":"","name":"ANDI ARAH MUBARAQ","nip":"","jabatan":"Quality Control","role":"QC Inspector","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"andiarahm16@gmail.com","tglMasuk":"4/13/2026","status":"Aktif","departemen":"Supporting","statusPegawai":"KONTRAK","sourceNo":38,"sourceDepartemen":"SUPPORTING","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;
INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-039','{"username":"umarchatib9","password":"","name":"M UMAR CHATIB","nip":"","jabatan":"Quantity Surveyor","role":"Quantity Surveyor","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"umarchatib9@gmail.com","tglMasuk":"4/15/2026","status":"Aktif","departemen":"Engineering","statusPegawai":"KONTRAK","sourceNo":39,"sourceDepartemen":"ENGGENERING","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;
INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-041','{"username":"muhzulfikarf14","password":"","name":"MUH ZULFIKAR","nip":"","jabatan":"PELAKSANA LAPANGAN","role":"Pelaksana Lapangan","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"muhzulfikarf14@gmail.com","tglMasuk":"4/15/2026","status":"Aktif","departemen":"Operational","statusPegawai":"KONTRAK","sourceNo":41,"sourceDepartemen":"operational","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;
INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-042','{"username":"nurulfadli00","password":"","name":"NURUL FADLI","nip":"","jabatan":"PELAKSANA LAPANGAN","role":"Pelaksana Lapangan","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"nurulfadli00@gmail.com","tglMasuk":"5/1/2026","status":"Aktif","departemen":"Operational","statusPegawai":"KONTRAK","sourceNo":42,"sourceDepartemen":"operational","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;
INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-043','{"username":"muhammadfadhly300","password":"","name":"MUHAMMAD FADHLY BURHANUDDIN","nip":"","jabatan":"PELAKSANA LAPANGAN","role":"Pelaksana Lapangan","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"Muhammadfadhly300@gmail.com","tglMasuk":"7/1/2026","status":"Aktif","departemen":"Operational","statusPegawai":"KONTRAK","sourceNo":43,"sourceDepartemen":"operational","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;
INSERT INTO app_records(collection,id,data_json,updated_at) VALUES('users','EMP-045','{"username":"anasmunandar18","password":"","name":"ANAS MUNANDAR","nip":"","jabatan":"PELAKSANA LAPANGAN","role":"Pelaksana Lapangan","unit":"NATARA KONSTRUKSI","atasan":"","telp":"","email":"anasmunandar18@gmail.com","tglMasuk":"7/21/2026","status":"Aktif","departemen":"Operational","statusPegawai":"KONTRAK","sourceNo":45,"sourceDepartemen":"operational","importMeta":{"source":"Data_Base_Karyawan.pdf","importedAt":"2026-09-08","emptyFieldsPreserved":true}}',CURRENT_TIMESTAMP) ON CONFLICT(collection,id) DO UPDATE SET data_json=excluded.data_json, updated_at=CURRENT_TIMESTAMP;

INSERT INTO app_sync_audit(id,collection,record_id,action)
VALUES(lower(hex(randomblob(16))),'users',NULL,'BULK_IMPORT_EMPLOYEES');

INSERT OR REPLACE INTO schema_meta(key,value,updated_at)
VALUES('employee_import_version','IMPORT-EMPLOYEES-23-20260908',CURRENT_TIMESTAMP);